[versions]
minSdk = "24"
targetSdk = "33"
compileSdk = "34"

# kotlin-ksp、compose-comiler 与 kotlin 版本相关联
agp = "8.7.3"
kotlin = "1.9.10"
buildTool = "34.0.0"


[libraries]
# junit
junit = { group = "junit", name = "junit", version = "4.13.2" }
# runner
runner = { group = "androidx.test", name = "runner", version = "1.5.2" }
# extJunit
extJunit = { group = "androidx.test.ext", name = "junit", version = "1.1.5" }
# espresso
espresso = { group = "androidx.test.espresso", name = "espresso-core", version = "3.5.1" }

appcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.6.1" }
fragment = { group = "androidx.fragment", name = "fragment-ktx", version = "1.7.1" }
activity = { group = "androidx.activity", name = "activity", version = "1.9.0" }
annotation = { group = "androidx.annotation", name = "annotation", version = "1.8.0" }
materialDesign = { group = "com.google.android.material", name = "material", version = "1.12.0" }
constraintLayout = { group = "androidx.constraintlayout", name = "constraintlayout", version = "2.1.4" }
coreKtx = { group = "androidx.core", name = "core-ktx", version = "1.13.1" }
datastorePreferences = { group = "androidx.datastore", name = "datastore-preferences", version = "1.0.0" }
lifecycleRuntime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version = "2.8.2" }
viewModel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version = "2.8.2" }
navigationFragmentKtx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version = "2.7.7" }

# gson ": "https://github.com/google/gson
gson = { group = "com.google.code.gson", name = "gson", version = "2.10.1" }
# coroutinesAndroid
coroutinesAndroid = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version = "1.7.3" }
# retrofit2 ": "https://github.com/square/retrofit
retrofit2 = { group = "com.squareup.retrofit2", name = "retrofit", version = "2.9.0" }
# retrofit2ConverterGson
retrofit2ConverterGson = { group = "com.squareup.retrofit2", name = "converter-gson", version = "2.9.0" }
# okHttpLogging
okHttpLogging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version = "4.11.0" }

# utilcodex
utilcodex = { group = "com.blankj", name = "utilcodex", version = "1.31.1" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
protobuf = { id = "com.google.protobuf", version = "0.9.4" }

[bundles]
